name = "base"
packages = [
    "filesystem",
    "glibc",
    "bash",
    "coreutils",
    "gcc",
    "binutils",
    "make",
    "pkgconf",
    "grep",
    "sed",
    "gawk",
    "findutils",
    "diffutils",
    "patch",
    "tar",
    "gzip",
    "xz",
    "zstd",
    "m4",
    "bison",
    "flex",
    "perl",
    "autoconf",
    "automake",
    "libtool",
    "patchelf",
]
